package com.vetrack.vetrack.Service;

import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.ImageFormat;
import android.graphics.Rect;
import android.graphics.YuvImage;
import android.hardware.Camera;
import android.media.Image;
import android.util.Log;

import org.jetbrains.annotations.NotNull;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URLEncoder;

import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.FormBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;

public class Network {
    private static String SERVER_URL = "http://121.196.150.184:8080/";
    private static Bitmap bitmapFromServer;
    private static Network network = null;

    public int getPrivacyState() {
        return privacyState;
    }

    public void setPrivacyState(int privacyState) {
        this.privacyState = privacyState;
    }

    private int privacyState = 0;

    public Network(){
        privacyState = 0;

    }

    public String download(String command){

        String map = null;
        OkHttpClient okHttpClient = new OkHttpClient();

        Request request = new Request.Builder()
                .url("http://121.196.150.184:8080/getMap")
                .build();
        Response response = null;
        try {
            response = okHttpClient.newCall(request).execute();
            String responseData = response.body().string();
            JSONArray jsonArray = new JSONArray(responseData);
            JSONObject jsonObject = jsonArray.getJSONObject(0);
            map = jsonObject.getString("map");

//            map = jsonObject.getString("map");
            Log.d("MAAAAAAAAAP",map);

        } catch (IOException | JSONException e) {
            e.printStackTrace();
//            map= "iVBORw0KGgoAAAANSUhEUgAABLAAAAMgCAYAAAAz4JsCAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsIAAA7CARUoSoAAABmzSURBVHhe7d0xbhznGYDh2ZxAcCulSm6QJkAukBgIpN7q0ltH0OoISp9O7ikEcHIEN7lBUkWqAgS6wWaXGsKMbEkUyd19Z/7nAX7wW9dje/nim5+b7TTtJgAAAACI+sX8EwAAAACSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0jbbadrNM4N69uZinsbx4OHjeQKA23v19Xfz9HlPv/9mngDg9t69fT1P43j56Mk8MTIbWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKRtttO0m2cG9Xw33iPwYrOZJwAAgOXw+xujsoEFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAEDaZjtNu3lmUM/eXMzTOB48fDxPAHB7r77+bp4+7+n338zTmN69fT1P4/B9o8Pzx5qM+Dy/fPRknhiZDSwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADSNttp2s0zg3q+G+8ReLHZzBMAcAq+b3BOnj+A5bOBBQAAAECagAUAAABAmoAFAAAAQJo7sJh+9YdX8zSOf/3t6TwBAKfgDiLOyfMHsHw2sAAAAABIE7AAAAAASBOwAAAAAEgTsAAAAABIc4k7LnEHAI7OJdqc27M3F/O0fi8fPZkngPWwgQUAAKzaSPEKYK0ELAAAAADSBCwAAAAA0gQsAAAAANIELAAAAADS/BVC/FUgAODofN/gnEa7xN1fIQTWyAYWAAAAAGkCFgAAAABpAhYAAAAAaQIWAACwWqPdfwWwVgIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAsEojXuD+8tGTeQJYFwELAAAAgDQBCwAAAIA0AQsAAFidEV8fBFgzAQsAAACANAELAABYFdtXAOsjYAEAAKyAv0AIrJmABQAArIbtK4B1ErAAAAAASBOwAACAVbB9BbBeAhYAAAAAaQIWAACweKNvX7nAHVg7AQsAAACANAELAABYNHdfAayfgAUAACyWeAUwBgELAABgwdx/BYxgs52m3TwzqOe78R6BF5vNPAEAsFS2r94TsIAR2MACAAAWR7wCGIuABQAALIp49SPbV8AoBCwAAGAxxCuAMQlYAADAIohXAOMSsAAAgDzx6qe8PgiMRMACAADSxCsABCwAACBLvALgQMACAACSxKuP8/ogMBoBCwAAyBGvALhOwAIAADIO4Uq8AuBDAhYAAJAgXN2M1weBEQlYAADAWdm6AuBzBCwAAOAshKsvZ/sKGJWABQAAnJRwBcCXErAAAICTEK7uxvYVMDIBCwAAOCrhCoC72mynaTfPDOr5brxH4MVmM08AAByDYHW/bF8BoxOwELAAALgTser4BCxgdAIWAhYAAB8lTp2feAXgDiwAAOAjxCsAKgQsAACAKNtXAO8JWAAAAACkCVgAAABBtq8AfiRgAQAAAJAmYAEAAMTYvgL4fwIWAAAAAGkCFgAAQIjtK4CfErAAAAAixCuAnydgAQAAAJAmYAEAAATYvgL4OAELAADgzMQrgE8TsAAAAABIE7AAAADOyPYVwOcJWAAAAGciXgHcjIAFAABwBuIVwM0JWAAAAACkCVgAAAAnZvsK4MsIWAAAACckXgF8OQELAADgRMQrgNsRsAAAAABIE7AAAABOwPYVwO0JWAAAAEcmXgHcjYAFAABwROIVwN0JWAAAAEciXgHcDwELAADgCMQrgPsjYAEAANwz8QrgfglYAAAA90i8Arh/AhYAAMA9Ea8AjkPAAgAAuAfiFcDxCFgAAAB3JF4BHJeABQAAcAfiFcDxCVgAAAC3JF4BnIaABQAAcAviFcDpCFgAAABf4BCuxCuA0xKwAAAAbki4AjgPAQsAAOAGxCuA8xGwAAAAPsErgwDnJ2ABAAB8hHAF0LDZTtNunhnUszcX8zSOBw8fzxMs27u3r+dpHH6RADidEb8nXuf/OQAdNrAAAACu8cogQI+ABQAAMBOuAJoELAAAYHi2rgDaBCwAAGBowhVAn4AFAAAMydYVwHIIWAAAwFCEK4DlEbAAAIAhCFcAyyVgAQAAqyZcASyfgAUAAKyScAWwHgIWAACwKsIVwPoIWAAAwCoIVwDrJWABAACLJlwBrJ+ABQAALM5VtBKuAMYgYAEAAIsgWgGMS8ACAACyRCsADgQsAAAgRbQC4EMCFgAAcFbXg5VoBcDPEbAAAICT+TBWCVYA3MRmO027eWZQz95czNM4Hjx8PE+wbO/evp6ncfhFB+B07vI90X+vAbhPAhYCFiyYgAUAAIzAK4QAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApG2207SbZwb1fDfeI/Bis5knWDb//gIAACOwgQUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAAABAmoAFAAAAQJqABQAAAECagAUAALfw32sHADguAQsAAL7AIVht9+fP146IBQDHJWABAMAN/bA/h2AFAJyWgAUAAJ9x2LD6y/78/fITAHBqAhYAAHzCP/fnsHX178tPAMA5CFgAAPAzrrauXl1+AgDOScACAIBrDuHqr/tj6woAOgQsAACYXYWrf1x+AgAqBCwAAIZ3CFfb/RGuAKBJwAIAYEhXrwoKVwDQJ2ABADCUq8vZvSoIAMshYAEAsHrXt61czg4AyyNgAQCwWj/sz1W0sm0FAMslYAEAsFr/mX/e1tP5JwBwXgIWAAB84Jf78+3+/PryEwBwbgIWAABc85v9+dP+fHX5CQAoELAAAGDvauvqj5efAIASAQsAgKEdwtXhritbVwDQJWABADCk6+HKXVcA0CZgAQAwlKtXBYUrAFgOAQsAgNU7RKvf7892f7wqCADLI2ABALBav9ufq2j128M/AAAWScACAGC1bFoBwDoIWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKQJWAAAAACkCVgAAAAApAlYAAAAAKRtttO0m2cG9ezNxTyN48HDx/MEy/bu7et5GsfLR0/mCeA09t+XP+vb/fnq/QgAHIENLAAAAADSBCwAAAAA0gQsAAAAANLcgYU7sGDB3IEFAACMwAYWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpAhYAAAAAaQIWAAAAAGkCFgAAAABpm+007eYZAAAAAHJsYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAAJAmYAEAAACQJmABAAAAkCZgAQAAABA2Tf8DawhqebNqVfYAAAAASUVORK5CYII=";

        }


        return map;
    }

    public void upload(String fileName, String dataString) throws Exception {
        OkHttpClient okHttpClient = new OkHttpClient();

        RequestBody requestBody = new FormBody.Builder()
                .add("filename", fileName)
                .add("imuFile", dataString)
                .build();

        Request request = new Request.Builder()
                .url(SERVER_URL+"postIMU")
                .post(requestBody)
                .build();
        okHttpClient.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                Log.e("net","FAILURE");
            }

            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                Log.d("net","SUCCESS");
            }
        });


    }

    /**
     * 把一个文件转化为字节
     *
     * @param file
     * @return byte[]
     * @throws Exception
     */
    public static byte[] getByte(File file) throws Exception {
        byte[] bytes = null;
        if (file != null) {
            InputStream is = new FileInputStream(file);
            int length = (int) file.length();
            if (length > Integer.MAX_VALUE)   //当文件的长度超过了int的最大值
            {
                System.out.println("this file is max ");
                return null;
            }
            bytes = new byte[length];
            int offset = 0;
            int numRead = 0;
            while (offset < bytes.length && (numRead = is.read(bytes, offset, bytes.length - offset)) >= 0) {
                offset += numRead;
            }
            //如果得到的字节长度和file实际的长度不一致就可能出错了
            if (offset < bytes.length) {
                System.out.println("file length is error");
                return null;
            }
            is.close();
        }
        return bytes;
    }

    public static Network getInstance(){
        if (network == null){
            network = new Network();
        }

        return network;
    }
}
